#spring.application.name=okariru

#spring.datasource.url=jdbc:postgresql://localhost:5432/okariru?currentSchema=core
#
## 3. Kredensial Database
#spring.datasource.username=postgres
#spring.datasource.password=Jakarta12345@



logging.level.org.springframework.security=DEBUG


app.storage.image-dir=${UPLOADS_DIR:uploads/images}


spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/okariru}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.security.jwt-secret=${JWT_SECRET:change-me-to-a-secret-key-at-least-32-chars}
app.security.jwt-ttl-minutes=${JWT_TTL_MINUTES:60}

#Konfigurasi JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA:public}
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

app.security.cors-allowed-origin=http://localhost:4200,https://okariru-fe.vercel.app


#REDIS

management.health.redis.enabled=true

app.redis.key-prefix=${REDIS_KEY_PREFIX:OTP:${spring.profiles.active:dev}}
app.redis.host=${REDIS_HOST:localhost}
app.redis.port=${REDIS_PORT:6379}
app.redis.timeout=${REDIS_TIMEOUT:1000ms}
#app.redis.username=${REDIS_USERNAME}
#app.redis.password=${REDIS_PASSWORD}
app.redis.lettuce-pool-max-active=100
app.redis.lettuce-pool-max-wait=100000ms
app.redis.lettuce-pool-max-idle=50
app.redis.lettuce-pool-min-idle=10

#SMTP

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jasonoke03@gmail.com
spring.mail.password=cudiywepbfbmbbyc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#FIREBASE (push notification FCM)
firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:firebase-service-account.json}
