#spring.application.name=okariru

spring.datasource.url=jdbc:postgresql://localhost:5432/okariru?currentSchema=core

# 3. Kredensial Database
spring.datasource.username=postgres
spring.datasource.password=Jakarta12345@

# 4. Konfigurasi Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false


management.health.redis.enabled=false

app.storage.image-dir=uploads/images