#spring.application.name=okariru

#spring.datasource.url=jdbc:postgresql://localhost:5432/okariru?currentSchema=core
#
## 3. Kredensial Database
#spring.datasource.username=postgres
#spring.datasource.password=Jakarta12345@

management.health.redis.enabled=false


app.storage.image-dir=uploads/images

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/okariru}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.security.jwt-secret=${JWT_SECRET:change-me-to-a-secret-key-at-least-32-chars}
app.security.jwt-ttl-minutes=${JWT_TTL_MINUTES:60}

#Konfigurasi JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

app.security.cors-allowed-origin=http://localhost:3000
